### ISSUE TITLE
Click Icon to Trigger Sort

### ISSUE THREAD

**Issue by GaryEarthling** [nightmode/sprucemarks#24]
It would be nice to be able to trigger a sort manually. As an example, [SuperSorter](https://chrome.google.com/webstore/detail/supersorter/hjebfgojnlefhdgmomncgjglmdckngij) does this when you click the icon - it's a nice feature as it allows you to trigger a sort immediately rather than waiting for the timeout.

**Comment by nightmode** [comment]
Try turning off the "Delay Sorting of Bookmarks" option to see if you like instant sorting. No clicks needed.

That option used to be mandatory for certain types of bookmark adding since sorting could make the UI disappear for a bookmark when it moved. The latest Chrome on Mac doesn't seem to need the delay, at least it seems that way with super quick testing so you might want to try it out too.

**Comment by nightmode** [comment]
Closing this issue as I like the automatic, no clicks approach to having bookmarks sorted.

I have however, added an investigational to-do to my sprucemarks private repo (aka the upcoming Patreon supported version) to see if the "Delay Sorting of New Bookmarks" option is still required. It probably is still required but I have not checked in a long time so I will recheck.
