### ISSUE TITLE
Feature: Sync settings via Chrome Sync or Google Drive.

### ISSUE THREAD

**Issue by cecoates** [nightmode/sprucemarks#25]
When setting up a new device/browser, choosing the same syncing options becomes a bit annoying.

Can they be synced via Chrome Sync?

If there's collision issues, being able to store the settings on Google Drive, and then import them manually as needed would be a close second in usability (like Tampermonkey or Stylish).

**Comment by nightmode** [comment]
I have always kept settings local because in a sync environment, two versions of Sprucemarks on two different computers could easily get in a sorting war. Computer One does A->B then Computer Two does B->A and so on. Bad for your CPU and very bad for your network traffic if the sorting gets into an infinite loop. Same deal with Sprucemarks and another sorting extension which could be local or on another computer.

Assuming you did have a sync environment, it might be possible to have Sprucemarks ONLY want to run in one place and each install of Sprucemarks somehow had its own ID. Then when a second, third, etc... version of Sprucemarks checks in, it could see that the "active" version of Sprucemarks is already set and know not to run. If you lost access to an "active" Sprucemarks on one of your computers you would need a way to set a new computer as the "active" Sprucemarks. Losing access to a computer, having connection issues, or even telling every version of Sprucemarks to "chill" while you change the options across all of them comes with a lot of complexity.

Have an import / export system might be a good solution but it also can be complicated. Exports would live outside the Sprucemarks extension and that means I could not upgrade them as options are changed, added, or removed during upgrades. I'd have to build an import / export system that could deal with EVERY permutation of options there ever was and keep adding to that complexity going forward. Ack, maintenance burden with added complexity of worrying about external files.

As a Sprucemarks user myself, I do think it would be cool to have preferred settings. I'm just not sure how to do that without over complicating things or risking sorting wars when two or more copies of Sprucemarks are running. I do like to think about the problem from time to time but so far... I don't have a good solution.

**Comment by nightmode** [comment]
I know I just wrote all that stuff above but I just had a thought...

What if ALL the Sprucemarks options EXCEPT for a new one were to be synced. That new option would simply be a ON/OFF switch with a very strongly worded warning that running Sprucemarks on more than one machine could cause bookmark sorting wars, high CPU, wasted network bandwidth, etc... 

Install a new version of Sprucemarks and it would get your preferred options synced EXCEPT for that ON/OFF switch which would default to false. It would be up to the user never to turn that button on in more than one location and... I could see that probably working ya?

**Comment by nightmode** [comment]
I have copied this issue to the private Sprucemarks repository since that is where all the Patreon changes are happening and because this repository is going POOF and disappearing on Jan 1, 2020.

Thanks for creating this cecoates. ^_^
